# Generated by Django 4.0.3 on 2022-03-20 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestTaskApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='TestTaskApp.autors'),
        ),
    ]
