# Generated by Django 4.0.3 on 2022-03-20 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestTaskApp', '0002_books_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='content',
            new_name='description',
        ),
    ]
